"""empty message

Revision ID: b8347ee57d33
Revises: 
Create Date: 2020-12-29 00:13:14.077319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8347ee57d33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_metadata',
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('script_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('table_name'),
    sa.UniqueConstraint('table_name')
    )
    op.create_table('washington_state_voters',
    sa.Column('state_voter_id', sa.String(), nullable=False),
    sa.Column('fname', sa.String(), nullable=True),
    sa.Column('mname', sa.String(), nullable=True),
    sa.Column('lname', sa.String(), nullable=True),
    sa.Column('name_suffix', sa.String(), nullable=True),
    sa.Column('birthdate', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('reg_st_num', sa.String(), nullable=True),
    sa.Column('reg_st_frac', sa.String(), nullable=True),
    sa.Column('reg_st_name', sa.String(), nullable=True),
    sa.Column('reg_st_type', sa.String(), nullable=True),
    sa.Column('reg_unit_type', sa.String(), nullable=True),
    sa.Column('reg_st_pre_direction', sa.String(), nullable=True),
    sa.Column('reg_st_post_direction', sa.String(), nullable=True),
    sa.Column('reg_st_unit_num', sa.String(), nullable=True),
    sa.Column('reg_city', sa.String(), nullable=True),
    sa.Column('reg_state', sa.String(), nullable=True),
    sa.Column('reg_zip_code', sa.String(), nullable=True),
    sa.Column('county_code', sa.String(), nullable=True),
    sa.Column('precinct_code', sa.String(), nullable=True),
    sa.Column('precinct_part', sa.String(), nullable=True),
    sa.Column('legislative_district', sa.String(), nullable=True),
    sa.Column('congressional_district', sa.String(), nullable=True),
    sa.Column('mail', sa.String(), nullable=True),
    sa.Column('mail_city', sa.String(), nullable=True),
    sa.Column('mail_zip', sa.String(), nullable=True),
    sa.Column('mail_state', sa.String(), nullable=True),
    sa.Column('mail_country', sa.String(), nullable=True),
    sa.Column('registrationdate', sa.String(), nullable=True),
    sa.Column('absentee_type', sa.String(), nullable=True),
    sa.Column('last_voted', sa.String(), nullable=True),
    sa.Column('status_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('state_voter_id'),
    sa.UniqueConstraint('state_voter_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('washington_state_voters')
    op.drop_table('dataset_metadata')
    # ### end Alembic commands ###
