"""empty message

Revision ID: 7ef3c4f2ba0c
Revises: 
Create Date: 2020-12-28 10:48:53.012083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ef3c4f2ba0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=True),
    sa.Column('reason_for_suspension', sa.String(), nullable=True),
    sa.Column('is_email_address_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_token', sa.String(), nullable=True),
    sa.Column('is_identity_verified', sa.Boolean(), nullable=True),
    sa.Column('email_address_salt', sa.String(), nullable=True),
    sa.Column('email_address_hash', sa.String(), nullable=True),
    sa.Column('password_salt', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('unique_identifiers', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers')
    # ### end Alembic commands ###
